/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VeryBasicCard {
        "description": string;
        "heading": string;
        "img": string;
    }
}
declare global {
    interface HTMLVeryBasicCardElement extends Components.VeryBasicCard, HTMLStencilElement {
    }
    var HTMLVeryBasicCardElement: {
        prototype: HTMLVeryBasicCardElement;
        new (): HTMLVeryBasicCardElement;
    };
    interface HTMLElementTagNameMap {
        "very-basic-card": HTMLVeryBasicCardElement;
    }
}
declare namespace LocalJSX {
    interface VeryBasicCard {
        "description"?: string;
        "heading"?: string;
        "img"?: string;
    }
    interface IntrinsicElements {
        "very-basic-card": VeryBasicCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "very-basic-card": LocalJSX.VeryBasicCard & JSXBase.HTMLAttributes<HTMLVeryBasicCardElement>;
        }
    }
}
